#!/bin/bash 
#PBS -l nodes=1:ppn=1 
#PBS -l walltime=9999:00:00 
#PBS -q cluster.q 
#PBS -N TmpGal_POWMES 
#PBS -V 
#PBS -M mahmoud@aims.ac.za 
#PBS -e /users/mhashim/lustre/mhashim/OxProj/TmpGal_POWMES.error 
#PBS -o /users/mhashim/lustre/mhashim/OxProj/TmpGal_POWMES.output 
#PBS -d ./ 

module purge
module add apps/plc/1.1
module add apps/idl/8.5
module add compilers/intel/intel-64.v13.1.046
module add mpi/openmpi/1.4.3/intel-64.v13.1.046

mpirun -np 1  /users/mhashim/lustre/mhashim/OxProj/EXC/POWMS /users/mhashim/lustre/mhashim/OxProj/Params/TmpGal_POWMES
